---  # Github labeler configuration file

# Add 'specs' label to any changes within 'docs' or `book` folder.
'specs':
  - changed-files:
      - any-glob-to-any-file: ['docs/**', 'book/**']

# Add 'ci' label to any changes within '.github' folder.
'ci':
  - changed-files:
      - any-glob-to-any-file: .github/**

# Add 'perf' label to PRs with perf/optimize/optimise in title (case-insensitive).
'perf':
  - pr-title:
      any: ['perf', 'optimize', 'optimise']

# Add 'bug' label to PRs with bug/fix in title (case-insensitive).
'bug':
  - pr-title:
      any: ['bug', 'fix']

# Add 'FRI' label to PRs with fri in title (case-insensitive).
'FRI':
  - pr-title:
      any: ['fri']

# Add 'refactoring' label to PRs with refactor/refactoring in title (case-insensitive).
'refactoring':
  - pr-title:
      any: ['refactor', 'refactoring']
