name: Deny

on:
  push:
    branches: ["main"]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
  pull_request:
    branches: ["*"]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          arguments: --all-features
